/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class MAV_HUBSAN_RECORDING_STATUS {
   public static final int MAV_HUBSAN_NOT_RECORDING = 0; /* camera is not recording. | */
   public static final int MAV_HUBSAN_IS_RECORDING = 1; /* camera is recording. | */
   public static final int MAV_HUBSAN_RECORDING_STATUS_ENUM_END = 2; /*  | */
}
            