/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class MAV_HUBSAN_QUAD_MODE {
   public static final int MAV_HUBSAN_NORMAL = 0; /* normal mode. | */
   public static final int MAV_HUBSAN_FREE_HEAD = 1; /* free head mode. | */
   public static final int MAV_HUBSAN_QUAD_MODE_ENUM_END = 2; /*  | */
}
            