/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Hubsan camera control command.
*/
public class MAV_HUBSAN_CAMERA_CONTROL {
   public static final int MAV_HUBSAN_CAMERA_ENTER_SNAP = 0; /* Enter snap function. | */
   public static final int MAV_HUBSAN_CAMERA_SNAP = 1; /* snap a picture. | */
   public static final int MAV_HUBSAN_CAMERA_ENTER_RECORD = 2; /* Enter record function. | */
   public static final int MAV_HUBSAN_CAMERA_RECORD_BEGIN = 3; /* record begin. | */
   public static final int MAV_HUBSAN_CAMERA_RECORD_STOP = 4; /* record stop. | */
   public static final int MAV_HUBSAN_CAMERA_VIDEO_OPEN = 5; /* video open. | */
   public static final int MAV_HUBSAN_CAMERA_VIDEO_STOP = 6; /* video stop. | */
   public static final int MAV_HUBSAN_CAMERA_VIDEO_1080P = 7; /* video switch to 1080p. | */
   public static final int MAV_HUBSAN_CAMERA_VIDEO_720P = 8; /* video switch to 720p. | */
   public static final int MAV_HUBSAN_CAMERA_VIDEO_VGA = 9; /* video switch to VGA. | */
   public static final int MAV_HUBSAN_CAMERA_CONTROL_ENUM_END = 10; /*  | */
}
            