/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class MAV_SD_STATUS {
   public static final int MAV_HUBSAN_SD_INSERTED = 0; /* SD card is inserted. | */
   public static final int MAV_HUBSAN_SD_ABSENCE = 1; /* SD card is absent. | */
   public static final int MAV_HUBSAN_SD_MOUNT_ERROR = 2; /* SD card is absent. | */
   public static final int MAV_SD_STATUS_ENUM_END = 3; /*  | */
}
            