/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE HUBSAN_QUAD_STATUS PACKING
package com.MAVLink.hubsan;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* quad status.
*/
public class msg_hubsan_quad_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS = 58;
    public static final int MAVLINK_MSG_LENGTH = 4;
    private static final long serialVersionUID = MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS;


      
    /**
    * System ID
    */
    public short target_system;
      
    /**
    * Component ID
    */
    public short target_component;
      
    /**
    * camera status,is recording or not,as defined by MAV_HUBSAN_RECORDING_STATUS enum
    */
    public short recording_status;
      
    /**
    * quadrotor mode status,as defined by MAV_HUBSAN_QUAD_MODE enum
    */
    public short quad_mode_status;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket();
        packet.len = MAVLINK_MSG_LENGTH;
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS;
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(target_component);
              
        packet.payload.putUnsignedByte(recording_status);
              
        packet.payload.putUnsignedByte(quad_mode_status);
        
        return packet;
    }

    /**
    * Decode a hubsan_quad_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        this.target_system = payload.getUnsignedByte();
              
        this.target_component = payload.getUnsignedByte();
              
        this.recording_status = payload.getUnsignedByte();
              
        this.quad_mode_status = payload.getUnsignedByte();
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_hubsan_quad_status(){
        msgid = MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_hubsan_quad_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_HUBSAN_QUAD_STATUS -"+" target_system:"+target_system+" target_component:"+target_component+" recording_status:"+recording_status+" quad_mode_status:"+quad_mode_status+"";
    }
}
        